### PR TITLE
Import ABC from collections.abc for Python 3.10 compatibility.

### LINKED ISSUE #25: Regression on Python 3.10: collections.iterable has been deprecated
Running on python 3.10 results in the error:

`AttributeError: module 'collections' has no attribute 'Iterable'`

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #25

### CODE REVIEW

**Comment by hhannine** [comment]
I have tested and verified that this works on Python 3.10.

**Comment by DizzyThermal** [comment]
Also tested this change working on Python 3.10. Looking forward to a pip release with this change included 👍
